extensions:
  dx_genstudio/genstudiopem/1:
    $include: src/genstudiopem/ext.config.yaml
    runtimeManifest:
      packages:
        genstudio-mlr-claims-app:
          license: Apache-2.0
          actions:
            veeva:
              function: src/genstudiopem/actions/veeva/index.js
              web: 'yes'
              runtime: 'nodejs:20'
              inputs:
                LOG_LEVEL: debug
                VEEVA_USERNAME: $VEEVA_USERNAME
                VEEVA_PASSWORD: $VEEVA_PASSWORD
                VEEVA_VAULT_URL: $VEEVA_VAULT_URL
                VEEVA_API_VERSION: $VEEVA_API_VERSION
                VEEVA_OBJECT_NAME: $VEEVA_OBJECT_NAME
                USE_VEEVA: $USE_VEEVA
              annotations:
                require-adobe-auth: true
                final: true
